;;;; -*- Mode: LISP; Base: 10; Syntax: ANSI-Common-lisp; Package: CL-USER -*-

(defpackage :cl-maprcli
  (:nicknames mapr)
  (:use #:cl #:drakma #:cl-json)
  (:export #:set-host
           #:set-authentication
           #:remove-assoc			;Need to be exported?
           #:rest-call				;Need to be exported?
           #:help

	   ;;; MapR API
	   #:acl-edit
	   #:acl-set
	   #:acl-sho
	   #:alarm-clear
	   #:alarm-clearall
	   #:alarm-config-load
	   #:alarm-config-save
	   #:alarm-list
	   #:alarm-names
	   #:alarm-raise
	   #:audit-cluster
	   #:audit-data
	   #:audit-info
	   #:cluster-gateway-delete
	   #:cluster-gateway-get
	   #:cluster-gateway-list
	   #:cluster-gateway-local
	   #:cluster-gateway-resolve
	   #:cluster-gateway-set
	   #:cluster-mapreduce-get
	   #:cluster-mapreduce-set
	   #:config-load
	   #:config-save
	   #:dashboard-info
	   #:dialhome-ackdial
	   #:dialhome-enable
	   #:dialhome-lastdialed
	   #:dialhome-metrics
	   #:dialhome-status
	   #:disk-add
	   #:disk-list
	   #:disk-listall
	   #:disk-remove
	   #:entity-info
	   #:entity-list
	   #:entity-modify
	   #:entity-remove
	   #:job-changepriority
	   #:job-kill
	   #:job-linklogs
	   #:job-table
	   #:license-add
	   #:license-addcrl
	   #:license-apps
	   #:license-list
	   #:license-listcrl
	   #:license-remove
	   #:license-showid
	   #:nagios-generate
	   #:node-allow-into-cluster
	   #:node-cldbmaster
	   #:node-failover
	   #:node-heatmap
	   #:node-list
	   #:node-listcldbs
	   #:node-listcldbzks
	   #:node-listzookeepers
	   #:node-maintenance
	   #:node-move
	   #:node-remove
	   #:node-services
	   #:node-topo
	   #:rlimit-get
	   #:rlimit-set
	   #:schedule-create
	   #:schedule-list
	   #:schedule-modify
	   #:schedule-remove
	   #:service-list
	   #:setloglevel-cldb
	   #:setloglevel-fileserver
	   #:setloglevel-hbmaster
	   #:setloglevel-hbregionserver
	   #:setloglevel-jobtracker
	   #:setloglevel-nfs
	   #:setloglevel-tasktracker
	   #:stream-assign-list
	   #:stream-create
	   #:stream-cursor-delete
	   #:stream-cursor-list
	   #:stream-delete
	   #:stream-edit
	   #:stream-info
	   #:stream-purge
	   #:stream-replica-add
	   #:stream-replica-autosetup
	   #:stream-replica-edit
	   #:stream-replica-list
	   #:stream-replica-pause
	   #:stream-replica-remove
	   #:stream-replica-resume
	   #:stream-upstream-add
	   #:stream-upstream-list
	   #:stream-upstream-remove
	   #:stream-topic-create
	   #:stream-topic-delete
	   #:stream-topic-edit
	   #:stream-topic-info
	   #:stream-topic-list
	   #:table-create
	   #:table-cf-colperm-get
	   #:table-cf-colperm-set
	   #:table-cf-colperm-delete
	   #:table-cf-create
	   #:table-cf-delete
	   #:table-cf-edit
	   #:table-cf-list
	   #:table-delete
	   #:table-edit
	   #:table-info
	   #:table-region-list
	   #:table-region-merge
	   #:table-region-pack
	   #:table-region-split
	   #:table-replica-add
	   #:table-replica-autosetup
	   #:table-replica-edit
	   #:table-replica-list
	   #:table-replica-pause
	   #:table-replica-remove
	   #:table-replica-resume
	   #:table-replica-elasticsearch-autosetup
	   #:table-replica-elasticsearch-edit
	   #:table-replica-elasticsearch-list
	   #:table-replica-elasticsearch-pause
	   #:table-replica-elasticsearch-resume
	   #:table-replica-elasticsearch-remove
	   #:table-upstream-add
	   #:table-upstream-list
	   #:table-upstream-remove
	   #:task-failattempt
	   #:task-killattempt
	   #:task-table
	   #:virtualip-add
	   #:virtualip-edit
	   #:virtualip-list
	   #:virtualip-move
	   #:virtualip-remove
	   #:volume-audit
	   #:volume-container-move
	   #:volume-container-switchmaster
	   #:volume-create
	   #:volume-fixmountpath
	   #:volume-info
	   #:volume-link-create
	   #:volume-link-remove
	   #:volume-list
	   #:volume-mirror-start
	   #:volume-mirror-stop
	   #:volume-modify
	   #:volume-mount
	   #:volume-move
	   #:volume-remove
	   #:volume-rename
	   #:volume-showmounts
	   #:volume-snapshot-create
	   #:volume-snapshot-list
	   #:volume-snapshot-preserve
	   #:volume-snapshot-remove
	   #:volume-unmount
	   #:volume-upgradeformat))

